language: java
env:
  global:
    - ENCRYPTION_LABEL="dc2141a8e04f"
    - GIT_NAME="Fishy"
    - GIT_EMAIL="deploy@fish.tip"
    - DEPLOY_BRANCH="master"

branches:
  except:
    - gh-pages

before_script:
  - sudo apt-get update
  - sudo apt-get install gcc-multilib g++-multilib -y

script:
  - java -jar ./Fishy.jar verify
  - sudo ./hugo_0.12_linux_386
  - sudo cp -a ./themes/fishy/static/. ./public/

after_success:
  - sudo chmod +x deploy.sh
  - sh ./deploy.sh
