language: java
branches:
  except:
    - gh-pages
before_script:
  - sudo apt-get update
  - sudo apt-get install gcc-multilib g++-multilib -y

script:
  - java -jar ./bin/Fishy.jar verify
  - sudo ./bin/hugo_0.12_linux_386

after_success:
  - ./deploy.sh

env:
global:
- ENCRYPTION_LABEL="dc2141a8e04f"
- GIT_NAME="Fishy"
- GIT_EMAIL="deploy@fish.tip"
- DEPLOY_BRANCH="master"
